WORDLE_WORDS = [
    # Curated, common 5‑letter English words (nouns, verbs, adjectives)
    # Everyday vocabulary; lowercase; no duplicates.
    "about", "above", "actor", "acute", "admit", "adult", "after", "again", "agent", "agree",
    "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone", "along", "aloud",
    "amber", "anger", "angle", "angry", "ankle", "apple", "apply", "arena", "argue", "arise",
    "arrow", "aside", "sleep", "asset", "audio", "avoid", "award", "aware", "awful", "badge",
    "baker", "basic", "beach", "beard", "begin", "being", "below", "bench", "berry", "birth",
    "black", "blade", "blame", "blank", "blast", "blend", "bless", "blind", "block", "blood",
    "board", "boast", "bonus", "booth", "bored", "brain", "brave", "bread", "break", "brick",
    "bride", "brief", "bring", "broad", "broke", "brown", "brush", "build", "bunch", "buyer",
    "cable", "cabin", "cacao", "candy", "carry", "catch", "cause", "chain", "chair", "chalk",
    "champ", "chart", "cheap", "check", "chess", "chest", "chili", "child", "chill", "china",
    "choir", "chose", "civic", "civil", "claim", "class", "clean", "clear", "clerk", "click",
    "climb", "clock", "close", "cloth", "cloud", "coach", "coast", "color", "count", "court",
    "cover", "crack", "craft", "crash", "cream", "creek", "crime", "cross", "crowd", "crown",
    "dance", "dated", "dealt", "death", "debit", "debut", "decaf", "decay", "depot", "delay",
    "delta", "demon", "dense", "depth", "dirty", "ditch", "doubt", "dozen", "draft", "drain",
    "drama", "drawn", "dream", "dress", "drink", "drive", "drops", "drove", "eager", "early",
    "earth", "elbow", "elder", "elect", "empty", "ended", "enter", "equal", "equip", "error",
    "event", "every", "exact", "extra", "faith", "false", "fancy", "fault", "favor", "feast",
    "fence", "fever", "field", "fifty", "fight", "final", "first", "flame", "flash", "fleet",
    "flesh", "floor", "flour", "focus", "force", "forth", "forum", "found", "fresh", "fried",
    "fruit", "front", "frost", "funny", "giant", "given", "glass", "globe", "glove", "grace",
    "grade", "grain", "grand", "grape", "graph", "grass", "grave", "great", "green", "greet",
    "grill", "group", "guard", "guess", "guest", "guide", "habit", "happy", "harsh", "heart",
    "heavy", "hello", "honey", "honor", "horse", "hotel", "house", "human", "humor", "hurry",
    "ideal", "image", "index", "input", "irony", "issue", "jeans", "joint", "judge", "juice",
    "knees", "knife", "knock", "label", "labor", "layer", "learn", "leave", "legal", "lemon",
    "level", "light", "limit", "linen", "liver", "local", "logic", "loose", "loyal", "lucky",
    "lunch", "lungs", "magic", "major", "maker", "march", "match", "maybe", "mayor", "means",
    "meant", "medal", "metal", "micro", "minor", "model", "money", "month", "moral", "motor",
    "mount", "mouse", "mouth", "movie", "music", "nails", "naked", "nasty", "never", "night",
    "noise", "north", "noted", "novel", "nurse", "ocean", "offer", "often", "olive", "onion",
    "order", "other", "ought", "owner", "paint", "panel", "paper", "party", "pasta", "peace",
    "peach", "penny", "phone", "photo", "piano", "piece", "pilot", "pizza", "place", "plane",
    "plant", "plate", "point", "porch", "pound", "power", "press", "price", "pride", "prime",
    "print", "prize", "proof", "proud", "queen", "quick", "quiet", "radio", "raise", "ranch",
    "range", "rapid", "ratio", "reach", "ready", "relax", "reply", "right", "rival", "river",
    "roast", "robot", "rocky", "rough", "round", "route", "royal", "rugby", "rural", "salad",
    "salty", "sauce", "scale", "scene", "score", "scout", "screw", "seats", "seems", "sense",
    "serve", "shade", "shake", "shall", "shape", "share", "sharp", "sheep", "sheet", "shelf",
    "shell", "shift", "shirt", "shock", "shoot", "short", "shown", "sight", "since", "skill",
    "sleep", "slice", "slide", "small", "smart", "smell", "smile", "smoke", "snack", "socks",
    "solar", "solid", "solve", "sound", "south", "space", "spare", "speak", "speed", "spice",
    "spicy", "spilt", "spine", "spoon", "sport", "stair", "stale", "stamp", "stand", "stare",
    "start", "state", "steam", "steel", "stick", "still", "stock", "stone", "store", "storm",
    "story", "stove", "study", "stuff", "style", "sugar", "sunny", "sweet", "table", "taken",
    "taste", "teach", "tears", "teeth", "thank", "their", "there", "these", "thick", "thing",
    "think", "third", "those", "three", "throw", "thumb", "tiger", "tight", "tired", "title",
    "today", "tooth", "touch", "towel", "tower", "trace", "track", "trade", "train", "treat",
    "trend", "trial", "trick", "truck", "trust", "truth", "twice", "uncle", "under", "unite",
    "union", "urban", "usage", "usual", "valid", "value", "video", "visit", "vital", "voice",
    "wagon", "waist", "watch", "water", "weigh", "wheel", "where", "which", "while", "white",
    "whole", "woman", "women", "world", "worry", "worth", "would", "wrist", "write", "young",
    "zebra",
]
